version: '3.3'
services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    networks:
      - int222-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_HOST: 'localhost'
      MYSQL_USER: int222
      MYSQL_PASSWORD: Yu`2rapD2,eUuq)T
    volumes:
      - ~/kaofood-data/mysql:/var/lib/mysql:rw
      # - "./database/init.sql:/docker-entrypoint-initdb.d/1.sql"
      # - "./database/insert.sql:/docker-entrypoint-initdb.d/2.sql"

  dev-backend:
    container_name: dev_spring
    image: ghcr.io/int222-31-33-43/kaofood_back-end:dev
    restart: always
    networks:
      - int222-network
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ~/kaofood-data/dev-backend:/app/storage:rw

  dev-web:
    container_name: dev_web
    image: ghcr.io/int222-31-33-43/kaofood_web:dev
    restart: always
    networks:
      - int222-network

  backend:
    container_name: spring
    image: ghcr.io/int222-31-33-43/kaofood_back-end:latest
    restart: always
    networks:
      - int222-network
    depends_on:
      - db
    volumes:
      - ~/kaofood-data/backend:/app/storage:rw

  web:
    container_name: web
    image: ghcr.io/int222-31-33-43/kaofood_web:latest
    restart: always
    networks:
      - int222-network
    ports:
      - "443:443"
    depends_on:
      - backend
      - dev-backend
      - dev-web

networks:
    int222-network:
      driver: bridge