version: '3.3'
services:
  db:
    container_name: int222_mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_HOST: 'localhost'
      MYSQL_USER: int222
      MYSQL_PASSWORD: Yu`2rapD2,eUuq)T
    volumes:
      - "./database/init.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./database/insert.sql:/docker-entrypoint-initdb.d/2.sql"
    networks:
        - int222-network
  dev-backend:
    container_name: int222_dev_back-end
    image: ghcr.io/int222-31-33-43/kaofood_back-end:dev
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - int222-network
  dev-web:
    container_name: int222_web
    image: ghcr.io/int222-31-33-43/kaofood_web:dev
    restart: always
    depends_on:
      - dev-backend
    networks:
      - int222-network
  backend:
    container_name: int222_back-end
    image: ghcr.io/int222-31-33-43/kaofood_back-end:latest
    restart: always
    depends_on:
      - db
    networks:
      - int222-network
  web:
    container_name: int222_web
    image: ghcr.io/int222-31-33-43/kaofood_web:latest
    restart: always
    ports:
      - "443:443"
    depends_on:
      - backend
      - dev-web
    networks:
      - int222-network
        
networks:
    int222-network:
      driver: bridge
