version: '3.3'
services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    networks:
      - int222-network
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Bangkok
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_HOST: 'localhost'
      MYSQL_USER: int222
      MYSQL_PASSWORD: Yu`2rapD2,eUuq)T
    volumes:
      - ~/kaofood-data/mysql:/var/lib/mysql:rw

  dev-backend:
    container_name: dev_spring
    image: ghcr.io/int222-31-33-43/kaofood_back-end:dev
    restart: always
    networks:
      - int222-network
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ~/kaofood-data/dev-backend:/app/storage:rw

  backend:
    container_name: spring
    image: ghcr.io/int222-31-33-43/kaofood_back-end:latest
    restart: always
    networks:
      - int222-network
    depends_on:
      - db
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ~/kaofood-data/backend:/app/storage:rw

  web:
    container_name: web
    image: ghcr.io/int222-31-33-43/kaofood_web:latest
    restart: always
    networks:
      - int222-network
    ports:
      - "443:443"
    depends_on:
      - backend
      - dev-backend
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ~/kaofood-data/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:rw
      - ~/kaofood-data/nginx/cloudflare/cloudflare.crt:/etc/nginx/certs/cloudflare.crt:ro
      - ~/kaofood-data/nginx/cloudflare:/etc/ssl:ro

networks:
    int222-network:
      driver: bridge