version: '3.3'
services:
  db:
    container_name: int222-mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_HOST: 'localhost'
      MYSQL_USER: int222
      MYSQL_PASSWORD: Yu`2rapD2,eUuq)T
    volumes:
      - "./database/init.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./database/data.sql:/docker-entrypoint-initdb.d/2.sql"
    networks:
        - int222-network
  back-end:
    container_name: int222_back-end
    image: ghcr.io/int222-31-33-43/kaofood_back-end:latest
    restart: always
    ports:
      - "8080:8088"
    depends_on:
      - db
    networks:
      - int221-network
  front-end:
    container_name: int222_front-end
    image: ghcr.io/int222-31-33-43/kaofood_front-end:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - int222-network
        
networks:
    int222-network:
      driver: bridge