USE kaofood;
-- User 
INSERT INTO `user`(email, password, fname, lname, phone, address, role) VALUES ('admin', 'admin', 'President', 'CEO', '0-112-2021-2564', 'KaoHome', 'Admin');
INSERT INTO `user`(email, password, fname, lname, phone, address, role) VALUES ('tu@mail.com', '904112', 'Tutoom', 'Manyriver', '0922253239', 'Home', 'Customer');

-- Type
INSERT INTO `category`(cateName, image, description) VALUES ('Noodle', '/images/type/noodle.png', null);
INSERT INTO `category`(cateName, image, description) VALUES ('Soup', '/images/type/soup.png', null);
INSERT INTO `category`(cateName, image, description) VALUES ('Salad', '/images/type/salad.png', null);
INSERT INTO `category`(cateName, image, description) VALUES ('Fried', '/images/type/fried.png', null);
INSERT INTO `category`(cateName, image, description) VALUES ('Dessert', '/images/type/dessert.png', null);

-- Menu
-- INSERT INTO [MENU](menuName, price, description, image, cateId) VALUES ('name', 10, 'des', '/images/menu/', 0);
INSERT INTO `menu`(menuName, price, description, image, cateId) VALUES ('Beef Noodle Soup', 40.50, 'Wonderfully fragrant and deliciously healthy, this simple Chinese Beef Noodle Soup makes the perfect warming meal.', '/images/menu/breefNoodleSoup.jpg', 1);
INSERT INTO `menu`(menuName, price, description, image, cateId) VALUES ('Spicy Shrimp Soup', 120.00, 'Tom Yum is probably the most famous of Thai soups and is popular not only in Thailand but in Thai restaurants worldwide. It is a clear, sour soup flavored with fragrant lemon grass, fresh galangal root and kaffir lime leaf. This potent herbal mixture is well known for its medicinal properties.', '/images/menu/spicyShrimpSoup.jpg', 2);
INSERT INTO `menu`(menuName, price, description, image, cateId) VALUES ('Tom Kha Gai', 100.00, 'Tom Kha Gai is cherished as a full-flavoured soup like Tom 0.Yum but made milder with coconut milk. Tom Kha is predominantly sour but also sweet, salty and deliciously coconutty. A good Tom Kha recipe calls for a smoothtextured soup. The coconut milk must not separate. Popular choices of protein are lean meats such as chicken breast and white fish.', '/images/menu/chickenCoconutSoup.jpg', 2);
INSERT INTO `menu`(menuName, price, description, image, cateId) VALUES ('Som Tam', 90.50, 'Som tam hails from Isaan in Northeastern Thailand and is one of the most popular dishes in Thailand. Som tam comes in a variety of styles, however, the classic som tam consists of shredded green papaya, tomatoes, carrots, peanuts, dried shrimp, runner beans, palm sugar, tamarind pulp, fish sauce, lime juice, garlic and plenty of chillies. The ingredients are mixed together using a mortar and pestle, which amplifies the flavours into a super moreish dish.', '/images/menu/somTam.jpg', 3);
INSERT INTO `menu`(menuName, price, description, image, cateId) VALUES ('Yam Pla Dook Foo', 80.00, '‘Fluffy’ and ‘crispy’ might be the best words to describe this dish. Catfish is fried in teeny tiny pieces (read “blown up”) creating an airy, fluffy and scrumptious fish salad. The secret to this dish is the pairing of the crispy fish with sweet, sour and spicy green mango salad. This dish is best enjoyed as an appetizer with a group of friends or as a beer snack.', '/images/menu/yamPlaDookFoo.jpg', 3);
INSERT INTO `menu`(menuName, price, description, image, cateId) VALUES ('Yam Talay', 180.00, 'This mixed seafood salad is not only delicious but is also a healthy meal option. Depending on where you are, this salad can have any combination of squid, shrimp, mussels, scallops or crabmeat in it. Added to the seafood medley are tomatoes, onions and rice glass noodles for good measure.', '/images/menu/yamTalay.jpg', 3);
INSERT INTO `menu`(menuName, price, description, image, cateId) VALUES ('Laab', 70.50, 'Laab is a northeastern-style salad with meat or mushroom and mint which originates in the northeastern province of Isan. Laab comes in a variety of styles including chicken, pork, and mushroom. It is not recommended for those who can’t handle spice as it tends to come with a hefty kick.', '/images/menu/laab.jpg', 3);
INSERT INTO `menu`(menuName, price, description, image, cateId) VALUES ('Stir-Fried Pumpkin', 60.00, 'Stir-fried pumpkin or “pad phuk tong” is one of the best vegetarian-friendly dishes in the Land of Smiles. While it is more difficult to find than a good helping of pad thai, you should definitely be on the lookout for this dish. Order it with a plate of brown rice if available and you’ll be laughing.', '/images/menu/padPhukTong.jpg', 4);
INSERT INTO `menu`(menuName, price, description, image, cateId) VALUES ('Pad Thai', 50.00, 'Pad thai is one of Thailands national dishes and is a go-to for tourists who are starting out their Thai cuisine exploration. Pad thai is a fried noodle dish which is usually made with shrimp or chicken, however, the vegetarian option is popular too. Pad thai is available on almost every street corner and is a cheap and tasty meal.', '/images/menu/padThai.jpg', 4);
INSERT INTO `menu`(menuName, price, description, image, cateId) VALUES ('Pad See Eiw', 75.00, 'This dish consists of wide rice noodles which are stir-fried in thick dark soy sauce with chicken, pork, or beef as well as either Chinese broccoli or cabbage. A flavorful but safe choice, it’s an excellent option for those who can’t handle spicier Thai dishes but want to branch out from pad thai. Foodies who like a little more kick can add dried chilli flakes, vinegar, or both.', '/images/menu/padSeeEiw.jpg', 4);
INSERT INTO `menu`(menuName, price, description, image, cateId) VALUES ('Pak Boong', 40.00, 'Pak boong (morning glory) is known for being extremely healthy. This spinach-like vegetable is typically fried and seasoned with soybean paste, soy sauce, garlic, chillies and more. Morning glory is salty, spicy, sour and crunchy all at the same time, satisfying anyone’s palette. This dish is often made with oyster sauce, however, the vegetarian option can easily be prepared.', '/images/menu/padBoong.jpg', 4);
INSERT INTO `menu`(menuName, price, description, image, cateId) VALUES ('Fried Rice', 45.00, 'Khao pad is maybe comparable to England’s love of sandwiches – consumed on mass khao pad is a Thai go-to. Khao pad simply translates to “fried rice” and is just that with some egg, onion and that’s about it. The dish usually comes with slices of cucumber to garnish and plenty of condiments are usually dumped on top to suit the consumer’s taste.', '/images/menu/friedRice.jpg', 4);
INSERT INTO `menu`(menuName, price, description, image, cateId) VALUES ('Pad Krapow', 45.00, 'A real Thai classic Pad Krapao ( which means basil stir-fry) topped with, or served over, a crispy fried egg with a slightly runny yolk.', '/images/menu/padKrapow.jpg', 4);
INSERT INTO `menu`(menuName, price, description, image, cateId) VALUES ('Panang', 90.50, 'Panang curry is a bit milder than its other curry counterparts in Thailand. It is for this reason that it remains a popular dish amongst tourists who are remaining in the spicy “safe zone.” Panang curry typically is served with shrimp, although vegetarian options are popular too.', '/images/menu/panang.jpg', 2);
INSERT INTO `menu`(menuName, price, description, image, cateId) VALUES ('Green Curry', 90.50, 'Green curry paste is traditionally made by pounding in a mortar green chillies, shallots, garlic, galangal, lemongrass, kaffir lime leaves, cilantro roots (coriander), and cumin seeds, white peppercorns, shrimp paste and salt.', '/images/menu/greenCurry.jpg', 2);
INSERT INTO `menu`(menuName, price, description, image, cateId) VALUES ('Khao Soi', 50.00, 'Khao Soi is a deliciously creamy and slightly spicy yellow curry dish unique to Northern Thailand. It will satisfy your craving for a Thai curry dish while still being delightfully out of the ordinary. We stumbled upon it within our first week of moving to Chiang Mai.', '/images/menu/khaoSoi.jpg', 1);
INSERT INTO `menu`(menuName, price, description, image, cateId) VALUES ('Fried Chicken', 30.25, 'Fried chicken may not be a uniquely Thai dish, but it’s extremely popular in Thailand. Gai tod is typically prepared by marinating chicken wings or drumsticks in a blend of spices and rice flour before deep frying the whole mixture. To add a little extra flavour, the chicken is also often served with a spicy dipping sauce like “nam jim.” Gai tod is best eaten with sticky rice and makes for a perfect on-the-go snack.', '/images/menu/gaiTod.jpg', 4);
INSERT INTO `menu`(menuName, price, description, image, cateId) VALUES ('Fried Vegetables', 25.75, 'This Thai classic will leave vegetarians and carnivores alike full and content. Most Thai dishes attempt to combine as many flavours as possible to make the most noteworthy dishes, and stir-fried vegetables are no exception. It’s worth not underestimating the flavour of these fried vegetables as they are mixed with a perfectly harmonious blend of sugar, salt and spices.', '/images/menu/friedVegetable.jpg', 4);
INSERT INTO `menu`(menuName, price, description, image, cateId) VALUES ('Kai Med Ma Muang', 100.00, 'Kai med ma muang is loved by locals and foreigners alike. This sweet and flavourful dish is stir-fried chicken with cashew nuts, soy sauce, honey, onions, chillies, pepper, mushrooms, basically whatever vegetables the chef has on hand. Simple, yet very tasty.', '/images/menu/', 4);
INSERT INTO `menu`(menuName, price, description, image, cateId) VALUES ('Thai Omelette', 25.00, 'his type of Thai-style omelet features multiple soft inner layers and crispy edges. It''s made of very few simple ingredients and, though some attention is needed when it comes to technique, the overall process is very quick and easy. Lots of smoking hot oil is necessary in ensuring success.', '/images/menu/thaiOmelette.jpg', 4);
INSERT INTO `menu`(menuName, price, description, image, cateId) VALUES ('Mango and Sticky Rice', 80.00, 'Looking for dessert? Look no further than the all-time crowd pleaser of mango and sticky rice. Kao niew ma muang is simple but extremely delicious, made with sticky rice, fresh mango slices, and lashings of sweet condensed milk.', '/images/menu/mangoAndStickyRice', 5);